# Generated by Django 5.1.6 on 2025-04-09 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='end_schedule',
            field=models.DateField(blank=True, null=True),
        ),
    ]
