# Generated by Django 5.1.6 on 2025-05-13 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0002_campaign_end_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='category',
            field=models.CharField(choices=[('IT', 'Technology'), ('MK', 'Marketing'), ('AD', 'Administration'), ('SL', 'Sales'), ('HR', 'Human Resources'), ('FI', 'Finance'), ('ED', 'Education'), ('HL', 'Healthcare'), ('OT', 'Other')], default='IT', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='campaign',
            name='education_level',
            field=models.CharField(choices=[('NONE', 'None'), ('HS', 'High School'), ('TEC', 'Technical'), ('TCH', 'Technologist'), ('UNI', 'University'), ('POS', 'Postgraduate'), ('PHD', 'Doctorate')], default='NONE', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='campaign',
            name='experience',
            field=models.CharField(default='Not specified', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='campaign',
            name='location',
            field=models.CharField(default='Not specified', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='campaign',
            name='modality',
            field=models.CharField(choices=[('ONSITE', 'On-site'), ('REMOTE', 'Remote'), ('HYBRID', 'Hybrid'), ('FLEX', 'Flexible')], default='ONSITE', max_length=10),
            preserve_default=False,
        ),
    ]
