# Generated by Django 5.1.6 on 2025-05-13 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0003_campaign_category_campaign_education_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='experience',
            field=models.CharField(choices=[('NONE', 'No experience'), ('1-3', '1 to 3 years'), ('4-7', '4 to 7 years'), ('8+', '8 or more years')], max_length=10),
        ),
    ]
