# Generated by Django 5.1.6 on 2025-05-18 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0005_alter_campaign_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='platform1',
            field=models.CharField(choices=[('GOOGLE', 'Google'), ('FACEBOOK', 'Facebook'), ('INSTAGRAM', 'Instagram')], default='GOOGLE', max_length=10),
        ),
        migrations.AddField(
            model_name='campaign',
            name='platform2',
            field=models.CharField(blank=True, choices=[('GOOGLE', 'Google'), ('FACEBOOK', 'Facebook'), ('INSTAGRAM', 'Instagram')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='platform3',
            field=models.CharField(blank=True, choices=[('GOOGLE', 'Google'), ('FACEBOOK', 'Facebook'), ('INSTAGRAM', 'Instagram')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='location',
            field=models.CharField(choices=[('AR', 'Argentina'), ('BR', 'Brazil'), ('CA', 'Canada'), ('CL', 'Chile'), ('CO', 'Colombia'), ('MX', 'Mexico'), ('US', 'United States'), ('VE', 'Venezuela'), ('DE', 'Germany'), ('ES', 'Spain'), ('FR', 'France'), ('GB', 'United Kingdom'), ('IT', 'Italy'), ('NL', 'Netherlands'), ('PL', 'Poland'), ('PT', 'Portugal'), ('CN', 'China'), ('IN', 'India'), ('ID', 'Indonesia'), ('JP', 'Japan'), ('KR', 'South Korea'), ('PH', 'Philippines'), ('SG', 'Singapore'), ('TH', 'Thailand')], default='Colmbia', max_length=2),
        ),
    ]
