# Generated by Django 5.1.6 on 2025-05-18 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0006_campaign_platform1_campaign_platform2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='platform1',
            field=models.CharField(blank=True, choices=[('GOOGLE', 'Google'), ('FACEBOOK', 'Facebook'), ('INSTAGRAM', 'Instagram')], max_length=10, null=True),
        ),
    ]
