# Generated by Django 5.1.6 on 2025-05-20 04:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0007_alter_campaign_platform1'),
    ]

    operations = [
        migrations.CreateModel(
            name='TargetUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_group', models.CharField(choices=[('18-24', '18-24'), ('25-34', '25-34'), ('35-44', '35-44'), ('45-54', '45-54'), ('55+', '55+')], max_length=5)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('location', models.CharField(choices=[('AR', 'Argentina'), ('BR', 'Brazil'), ('CA', 'Canada'), ('CL', 'Chile'), ('CO', 'Colombia'), ('MX', 'Mexico'), ('US', 'United States'), ('VE', 'Venezuela'), ('DE', 'Germany'), ('ES', 'Spain'), ('FR', 'France'), ('GB', 'United Kingdom'), ('IT', 'Italy'), ('NL', 'Netherlands'), ('PL', 'Poland'), ('PT', 'Portugal'), ('CN', 'China'), ('IN', 'India'), ('ID', 'Indonesia'), ('JP', 'Japan'), ('KR', 'South Korea'), ('PH', 'Philippines'), ('SG', 'Singapore'), ('TH', 'Thailand')], max_length=2)),
                ('interests', models.CharField(choices=[('TECH', 'Technology'), ('BUSINESS', 'Business'), ('EDUCATION', 'Education'), ('ENTERTAINMENT', 'Entertainment'), ('SPORTS', 'Sports'), ('HEALTH', 'Health & Fitness'), ('FOOD', 'Food & Dining'), ('TRAVEL', 'Travel'), ('FASHION', 'Fashion'), ('OTHER', 'Other')], max_length=20)),
                ('education_level', models.CharField(choices=[('NONE', 'None'), ('HS', 'High School'), ('TEC', 'Technical'), ('TCH', 'Technologist'), ('UNI', 'University'), ('POS', 'Postgraduate'), ('PHD', 'Doctorate')], max_length=10)),
                ('experience', models.CharField(choices=[('NONE', 'No experience'), ('1-3', '1 to 3 years'), ('4-7', '4 to 7 years'), ('8+', '8 or more years')], max_length=10)),
                ('click_rate', models.FloatField(default=0.0)),
                ('conversion_rate', models.FloatField(default=0.0)),
                ('engagement_score', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CampaignTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_score', models.FloatField(default=0.0)),
                ('is_selected', models.BooleanField(default=False)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='ad.campaign')),
                ('target_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='ad.targetuser')),
            ],
            options={
                'unique_together': {('campaign', 'target_user')},
            },
        ),
    ]
