# Generated by Django 5.1.6 on 2025-05-20 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0008_targetuser_campaigntarget'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CampaignTarget',
        ),
        migrations.DeleteModel(
            name='TargetUser',
        ),
    ]
