# Generated by Django 5.1.6 on 2025-05-21 03:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0009_delete_campaigntarget_delete_targetuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('impressions', models.IntegerField()),
                ('clicks', models.IntegerField()),
                ('ctr', models.FloatField()),
                ('conversions', models.IntegerField()),
                ('conversion_rate', models.FloatField()),
                ('cpc', models.FloatField()),
                ('cpa', models.FloatField()),
                ('spend', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='ad.campaign')),
            ],
        ),
    ]
