# Generated by Django 5.1.6 on 2025-05-21 04:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ad", "0009_delete_campaigntarget_delete_targetuser"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdInteraction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("impressions", models.IntegerField(default=0)),
                ("clicks", models.IntegerField(default=0)),
                ("conversions", models.IntegerField(default=0)),
                ("date", models.DateField(default=django.utils.timezone.now)),
                (
                    "ad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="ad.campaign"
                    ),
                ),
            ],
        ),
    ]
