# Generated by Django 5.1.6 on 2025-05-21 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ad", "0010_adinteraction"),
    ]

    operations = [
        migrations.AddField(
            model_name="adinteraction",
            name="platform",
            field=models.CharField(default="GOOGLE", max_length=20),
            preserve_default=False,
        ),
    ]
