# Generated by Django 5.1.6 on 2025-05-20 04:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ad', '0009_delete_campaigntarget_delete_targetuser'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edad', models.IntegerField()),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1)),
                ('interes', models.CharField(max_length=50)),
                ('actividad', models.CharField(choices=[('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja')], max_length=10)),
                ('dispositivo', models.CharField(choices=[('movil', 'Móvil'), ('tablet', 'Tablet'), ('pc', 'PC')], max_length=10)),
                ('hora_activa', models.IntegerField()),
                ('dias_activos', models.IntegerField()),
                ('gasto_promedio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('frecuencia_compra', models.IntegerField()),
                ('ultima_compra', models.IntegerField()),
                ('clicks_previos', models.IntegerField()),
                ('conversion_previo', models.BooleanField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CampaignSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('probability', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ad.campaign')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_segmentation.userprofile')),
            ],
            options={
                'unique_together': {('campaign', 'user_profile')},
            },
        ),
    ]
